
export const ALBUMS__GET_BY_ARTIST = 'ALBUMS__GET_BY_ARTIST';
export const ALBUMS__RESET = 'ALBUMS__RESET';

export const ARTISTS__FETCH_ONE = 'ARTISTS__FETCH_ONE';
export const ARTISTS__QUERY = 'ARTISTS__QUERY';

export const USER__FETCH_OAUTH = 'USER__FETCH_OAUTH';
